#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# if mouse_modifier is set to 'cmd' this prevents cmd + right mouse to select!
yabai -m config mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_shadow off \
	window_opacity off \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.80 \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	auto_balance off \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	layout float \
	top_padding 5 \
	bottom_padding 5 \
	left_padding 5 \
	right_padding 5 \
	window_gap 06 \
	external_bar all:25:0 # padding top:bottom

# no tiling on space one
# BUT apps will not respect top padding for the bar
# yabai -m config --space 1 layout float

# Floating for special apps
yabai -m rule --add app="^KeePassXC$" sticky=off layer=normal manage=off
yabai -m rule --add app="^ForkLift$" sticky=off layer=normal manage=off
yabai -m rule --add app="^Font Book$" sticky=off layer=normal manage=off
yabai -m rule --add app="^System Preferences$" sticky=off layer=normal manage=off
yabai -m rule --add app="^TinkerTool$" sticky=off layer=normal manage=off
yabai -m rule --add app="^Docker Desktop$" sticky=off layer=normal manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=off layer=normal manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# Some Goland settings, in case you are using it. float Goland Preference panes
yabai -m rule --add app='Goland IDEA' title='^$' sticky=off layer=normal manage=off
yabai -m rule --add app='Goland IDEA' title='Project Structure' sticky=off layer=normal manage=off
yabai -m rule --add app='Goland IDEA' title='Preferences' sticky=off layer=normal manage=off
yabai -m rule --add app='Goland IDEA' title='Edit configuration' sticky=off layer=normal manage=off

# Handling sketchybar window events
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

echo "yabai configuration loaded.."
